export const ADD_POST = 'ADD_POST'; 
export const INPUT_POST = 'INPUT_POST';
export const INPUT_COMMENT = 'INPUT_COMMENT';
export const UPDATE_POST = 'UPDATE_POST';
export const UPDATE_COMMENT = 'UPDATE_COMMENT';
export const FETCH_POST = 'FETCH_POST';
export const FETCH_POST_DATA = 'FETCH_POST_DATA';
export const ADD_COMMENT = 'ADD_COMMENT';
export const ADD_REPLY = 'ADD_REPLY';
export const POST_ADD_LIKE = 'POST_ADD_LIKE';
export const POST_REMOVE_LIKE = 'POST_REMOVE_LIKE';
export const COMMENT_ADD_LIKE = 'COMMENT_ADD_LIKE';
export const COMMENT_REMOVE_LIKE = 'COMMENT_REMOVE_LIKE';
export const REPLY_ADD_LIKE = 'REPLY_ADD_LIKE';
export const REPLY_REMOVE_LIKE = 'REPLY_REMOVE_LIKE';
export const POST_LOADING = 'POST_LOADING';
export const POST_ERROR = 'POST_ERROR';
export const FETCH_REPLY_COMMENT = 'FETCH_REPLY_COMMENT';
export const FETCH_LIKE_COMMENT =  'FETCH_LIKE_COMMENT';
export const FETCH_POST_DATA_COMPLETE = 'FETCH_POST_DATA_COMPLETE';

export const EMAIL_PASSWORD_AUTH_SIGNIN = 'EMAIL_PASSWORD_AUTH_SIGNIN';
export const EMAIL_PASSWORD_AUTH_SIGNOUT = 'EMAIL_PASSWORD_AUTH_SIGNOUT';
export const AUTH_LOADING = 'AUTH_LOADING';
export const AUTH_ERROR = 'AUTH_ERROR';
export const FETCH_USER = 'FETCH_USER';
export const USER_POST = 'USER_POST';
export const UPDATE_USER = 'UPDATE_USER';




